# Generated by Django 5.0 on 2023-12-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_travel_alter_feeding_options_finch_travel_spots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='travel_spots',
            new_name='travel_places',
        ),
    ]
